name: flutter_roro
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^3.0.1
  country_picker: ^2.0.21
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  intl: ^0.18.1
  polyline_codec: ^0.1.6
  rive: ^0.11.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CherryBombOne
      fonts:
        - asset: assets/fonts/CherryBombOne-Regular.ttf
